### ISSUE TITLE
Why linkbench is generating linktable rows with id2 that does not exists on nodetable?

### ISSUE THREAD

**Issue by luccasmaso** [facebook/linkbench#25] opened 2015-03-18 17:39 UTC
Executing the example on the README and running the load pahse of the benchmark with the mysql database example, I figured some problems in the `linktable`.

First, the id range for nodes was seted from 1 to 1000. When running, I have got the 1000 rows in the `nodetable`, ok. However, in the `linktable`, there are a lot of rows with `id2` that are out of this range, for example, 1001. 

Is this a bug or some behavior Im not following?
Because this lacks consistency. When I work with some graph database, I need the presence of some vertex with the id2 to make the relationship.

Thanks.

**Comment by mdcallag** [comment] 2015-03-18 17:41
I don't know. I will look at this in the next 1 or 2 weeks. Before then can you try with a larger id range (1M rather than 1000)?

**Comment by luccasmaso** [comment] 2015-03-18 17:44
Ok, thanks, I will give a try. Im using Linkbench for a thesis and running against several nosql databases, but Im still stuck on load phase. 

Hope you can help!

**Comment by mdcallag** [comment] 2015-03-18 17:51
What  is your deadline/schedule?

On Wed, Mar 18, 2015 at 10:44 AM, Luccas Maso <notifications@github.com>
wrote:

> Ok, thanks, I will give a try. Im using Linkbench for a thesis and running
> against several nosql databases, but Im still stuck on load phase.
>
> Hope you can help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/linkbench/issues/25#issuecomment-83084079>.
>



-- 
Mark Callaghan
mdcallag@gmail.com

**Comment by timarmstrong** [comment] 2015-03-18 18:10
The question has come up in the past - LinkBench's data model is less strict than that of some graph databases.  In particular, LinkBench's data model allows dangling links.  There is a conceptual reason for this - they can represent links to other shards of a distributed graph database or even external entities.  There's are also pragmatic reasons that I'll mention later.

It's probably not too hard to solve your immediate problem by tweaking id2 generation so they're all in range [0..maxid1]. 

You would still run into further problems though, because:
* node deletions in LinkBench don't need to remove associated links (I guess it's ok if they do, it's just going to be slower).
* edge additions could refer to an id1/id2 node that was previously deleted - in this case if you skip adding the edge it arguably gives your database an unfair advantage.  This happens because the LinkBench client is mostly stateless by design and doesn't track nodes are present/absent in the database.

If your graph database requires nodes for both ends of every edge, your best solution is to modify your adapter to automatically create fake nodes if a real node is not present.  This would bring it more into line with LinkBench's data model.

There's a little more discussion on this issue - https://github.com/facebook/linkbench/issues/12#issuecomment-37576962

**Comment by luccasmaso** [comment] 2015-03-20 20:42
Hi guys, thank you so much for the support! 
I have tried setting the id2 to 1M and it worked. However I will give a try in what timarmstrong said because for now is too much slow to load 1M nodes for only test and some validation purposes.
About my thesis, it will be for the next few months.

Thanks

**Comment by facebook-github-bot-3** [comment] 2015-08-04 18:02
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by maykov** [comment] 2015-08-12 00:13
Dangling links are by design. Closing the issue for now.

**Closed by maykov** 2015-08-12 00:13 UTC
